version: "3.8" # https://docs.docker.com/compose/compose-file/
services:
  app:
    container_name: mando_bot
    restart: always
    environment:
      - NODE_ENV="production"
      - PORT="4500"
      - MONGO_CONNECTION_URI="mongodb://mongodb:27017/"
    build: ./
    ports:
      - "4500:4500"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: